/**
 * Wave 3A — partner-side KYC signed upload (canon §4.6, §3.4).
 *
 * POST /api/partner/kyc/upload
 *   { doc_type: 'rc'|'ice'|'patente'|... , content_type?, ext? }
 *
 * Returns a single-shot signed upload token + path for the private
 * `kyc-documents` bucket. Path is forced to `partners/<partner_id>/<uuid>.<ext>`.
 * The DB row is inserted up-front with `status='submitted'` and the storage
 * path; a follow-up `/api/partner/kyc/record` endpoint flips the row to
 * `under_review` once the upload completes (admin reviews from there).
 *
 * Hard rules (canon §6 F12):
 *   - private bucket only
 *   - never `getPublicUrl`
 *   - signed READ URLs are 15 min max — generated by admin tools, not here
 */
import { NextResponse } from "next/server"
import { z } from "zod"
import { randomUUID } from "node:crypto"
import { getUserRole } from "@/lib/auth/get-user-role"
import { createClient } from "@/lib/supabase/server"
import { createServiceRoleClient } from "@/lib/supabase/service-role"

export const dynamic = "force-dynamic"
export const runtime = "nodejs"

const ALLOWED_DOCS = new Set([
  "rc", "ice", "patente", "cnss", "statuts", "pouvoir",
  "cin", "passport", "rib", "attestation_assurance",
  "permis_conduire", "carte_grise", "assurance_vehicule",
  "casier_judiciaire", "diplome", "licence_federale",
  "declaration_micro_entreprise", "attestation_halal",
  "autorisation_municipale",
])

const ALLOWED_MIMES = new Set([
  "image/jpeg",
  "image/png",
  "image/webp",
  "application/pdf",
])

const bodySchema = z.object({
  doc_type: z.string().min(1).max(40),
  content_type: z.string().min(3).max(80).optional(),
  ext: z.string().min(1).max(8).optional(),
})

function safeExt(raw: string | undefined): string {
  const v = (raw || "bin").toLowerCase().replace(/[^a-z0-9]/g, "").slice(0, 5)
  return v || "bin"
}

export async function POST(request: Request) {
  const userInfo = await getUserRole()
  if (!userInfo || userInfo.role !== "partner") {
    return NextResponse.json(
      { success: false, error: "unauthenticated" },
      { status: 401 },
    )
  }

  let body: z.infer<typeof bodySchema>
  try {
    body = bodySchema.parse(await request.json())
  } catch {
    return NextResponse.json({ success: false, error: "invalid_body" }, { status: 400 })
  }
  if (!ALLOWED_DOCS.has(body.doc_type)) {
    return NextResponse.json(
      { success: false, error: "doc_type_not_allowed" },
      { status: 400 },
    )
  }
  if (body.content_type && !ALLOWED_MIMES.has(body.content_type)) {
    return NextResponse.json(
      { success: false, error: "content_type_not_allowed" },
      { status: 400 },
    )
  }

  // Resolve the partner the caller belongs to. Owner staff or active partner_staff.
  const sr = createServiceRoleClient()
  const { data: partner } = await sr
    .from("partners")
    .select("id, status")
    .eq("email", userInfo.email)
    .maybeSingle()
  if (!partner) {
    return NextResponse.json(
      { success: false, error: "partner_not_found" },
      { status: 404 },
    )
  }

  // Build storage path. ALWAYS prefix with partners/<id>/ — bucket policy
  // enforces the prefix as defence-in-depth.
  const objectName = `partners/${partner.id}/${randomUUID()}.${safeExt(body.ext)}`

  // Service-role-bound storage create. The signed-upload token is a one-shot
  // and is the only secret we ever return to the partner client.
  const supabase = await createClient()
  const { data: signed, error: signErr } = await supabase.storage
    .from("kyc-documents")
    .createSignedUploadUrl(objectName)

  if (signErr || !signed?.token) {
    return NextResponse.json(
      { success: false, error: signErr?.message ?? "sign_upload_failed" },
      { status: 500 },
    )
  }

  // Insert the kyc_documents row up-front. status='submitted' until upload
  // completes; Wave 3B can add a /record endpoint to flip to under_review.
  const { data: doc, error: insErr } = await sr
    .from("kyc_documents")
    .insert({
      partner_id: partner.id,
      doc_type: body.doc_type,
      file_path: signed.path,
      status: "submitted",
    })
    .select("id, status, file_path")
    .single()
  if (insErr) {
    return NextResponse.json(
      { success: false, error: insErr.message },
      { status: 500 },
    )
  }

  return NextResponse.json({
    success: true,
    doc_id: doc.id,
    path: signed.path,
    token: signed.token,
    bucket: "kyc-documents",
  })
}
