-- Wave 1B — Money Truth migration
-- ============================================================================
-- Source canon: docs/canon/economy-payments.locked.md §7 + §6 FORBIDDEN #3.
-- Founder F5: PSP_AUTO_TOPUP_ENABLED=false at launch (manual-only).
--
-- This migration ships THREE money-truth fixes:
--   1. Adds `client_idempotency_key uuid UNIQUE` on `payment_transactions`
--      so the parent top-up route can dedupe duplicate POSTs (replay safety).
--   2. Defensive alias `add_user_xp` → `add_xp_to_user` so any legacy caller
--      that slipped past the canon-precommit gate receives a usable RPC and
--      not a 42883 (function does not exist). The alias is marked for sunset
--      and SHOULD be dropped at the next major.
--   3. (Reserved) PARENT_TOPUP_MAX_DH limit hook — left to F5 follow-up.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Idempotency key on payment_transactions (canon §4.1).
-- ---------------------------------------------------------------------------
ALTER TABLE public.payment_transactions
  ADD COLUMN IF NOT EXISTS client_idempotency_key UUID;

CREATE UNIQUE INDEX IF NOT EXISTS idx_payment_transactions_client_idempotency_key
  ON public.payment_transactions (client_idempotency_key)
  WHERE client_idempotency_key IS NOT NULL;

COMMENT ON COLUMN public.payment_transactions.client_idempotency_key IS
  'UUID generated by the parent top-up form on mount (NOT submit). Server '
  'rejects duplicate POSTs with the same key by returning the existing row '
  'idempotently. See docs/canon/economy-payments.locked.md §4.1.';

-- ---------------------------------------------------------------------------
-- 2. Defensive alias: add_user_xp → add_xp_to_user.
--    DEFENSIVE ONLY. Marked for sunset — remove in the major after Wave 1B.
--    The canon-precommit gate (CANON-XP-001) blocks net-new callers in
--    app code; this alias merely keeps any pre-existing caller from 500ing
--    in production until we delete it.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.add_user_xp(
  p_user_id     UUID,
  p_xp_amount   INTEGER,
  p_source_type TEXT,
  p_source_id   UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  -- DEPRECATED: forwards to canonical add_xp_to_user. Slated for removal.
  RETURN public.add_xp_to_user(
    p_teen_id          := p_user_id,
    p_xp_amount        := p_xp_amount,
    p_source_type      := p_source_type::varchar,
    p_source_category  := NULL::varchar,
    p_source_id        := p_source_id,
    p_description      := 'legacy add_user_xp shim'
  );
END;
$$;

COMMENT ON FUNCTION public.add_user_xp(UUID, INTEGER, TEXT, UUID) IS
  'DEPRECATED defensive alias for add_xp_to_user. Wave 1B 095. Remove after '
  'next major release once all callers are confirmed canonical.';

GRANT EXECUTE ON FUNCTION public.add_user_xp(UUID, INTEGER, TEXT, UUID)
  TO authenticated, service_role;

COMMIT;
